language: ruby
cache: bundler
rvm:
- 2.0.0
script: CODECLIMATE_REPO_TOKEN=6298f1286a1bcb4263816164ce1a3ef5d6b8f7159f69b54c20c6fdc39ec3d173 bundle exec rake ci
deploy:
  provider: rubygems
  api_key:
    secure: QQevlWTpIwUsCHZf2kAbBc6YjedIV+T5IBvvNRnU5Uj/u+gbmpwtYqHuS0SYPGlAiCQFld7FpJ1K20FAsygUZqQaQqr8L85d++0qvaDqTmXm7OgLX4Q1ZxVYgCDA3MnDUY/oLnWmcQ7FwcvQH4yceuNXkBKLRm+OW4c2USvGNDk=
  gem: alcove
  on:
    repo: ioveracker/Alcove
    all_branches: true
    tags: true
